config/routes.rb
Rails.application.routes.draw do

root to:"items#index"
  devise_for :users
  
  
  resources :items
  resources :carts
  resources :orders
  resources :users
  resources :cart_items

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/order.rb
class Order < ApplicationRecord
  after_create :order_recap
  
  
  belongs_to :user

  has_many :item_orders
  has_many :items, through: :item_orders

    
  def order_recap
    UserMailer.order_recap_email(self).deliver_now
    UserMailer.admin_order_email(self).deliver_now
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
  end
  
  def new
    @order = Order.create(user:current_user, total_amount:params[:total].to_f)
    
    @amount = @order.total_amount
    @stripe_amount = @amount*100
  end

  def create
    
    # Before the rescue, at the beginning of the method
    @order = Order.where(user:current_user).last
    @stripe_amount = (@order.total_amount*100).to_i # LIGNE D ORIGINE 500
    puts "#"*100
    puts "@stripe_amount = #{@stripe_amount}"
    puts "#"*100

    begin
      customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
      })
      charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @stripe_amount, 
      description: "Acheter un produit", 
      currency: 'eur',
      })
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path
    end
    # After the rescue, if the payment succeeded


    # Opération de vidage du panier 
    all_cart_items = CartItem.all
    all_cart_items.each do |cart_item|
      if cart_item.cart == current_user.cart
        
        cart_item.destroy
        
      end
    end
    redirect_to order_path(@order)
  end
 

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end



end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 pt-5">
    <div class="alert alert-success" role="alert">
  
      <h1 class="text-center">La commande est bien passée ! Merci !</h1>
      <div class="d-flex justify-content-center pt-5">
    <%= link_to  "Continuer le Shopping", root_path, class: "btn btn-secondary btn-lg me-5"%>
</div>
    </div>
  </div>

</div>
</div>

app/views/orders/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 pt-5">
    <div class="alert alert-warning" role="alert">
  
      <h1 class="text-center">Cliquez sur le lien suivant pour procéder au paiement de <%= @amount %>0€ </h1>
      <div class="d-flex justify-content-center pt-5">
      <%= form_tag orders_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-description="Cute Cat Shop"
  data-amount=<%= @stripe_amount %>
  data-currency="eur"
  data-locale="auto"></script>
<% end %>
</div>
    </div>
  </div>

</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 pt-5">
    <div class="alert alert-success" role="alert">
  
      <h1 class="text-center">La commande est bien passée ! Merci !</h1>
      <div class="d-flex justify-content-center pt-5">
    <%= link_to  "Continuer le Shopping", root_path, class: "btn btn-secondary btn-lg me-5"%>
</div>
    </div>
  </div>

</div>
</div>