config/routes.rb
Rails.application.routes.draw do

root to:"items#index"
  devise_for :users
  
  
  resources :items
  resources :carts
  resources :orders
  resources :users
  resources :cart_items

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/cart.rb
class Cart < ApplicationRecord
   belongs_to :user

  has_many :cart_items
  has_many :items, through: :cart_items

  validates :user_id, uniqueness: true
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_cart_owner

  def new
  end

  def create
  end

  def index
  end

  def show
    # Code de Julien pour montrer à Nico [A SUPPRIMER]
    @cart = current_user.cart
    @total = 0

    puts "#"*50
    puts "total (AVANT le each) = #{@total}"
    puts "#"*50

    @cart.items.each do |item|
      @total = @total + item.price
    end

    puts "#"*50
    puts "total (APRES le each) = #{@total}"
    puts "#"*50
  end

  def update

  end

  def destroy
  end

  def edit
  end

  private

  def check_cart_owner
    cart_owner = Cart.find(params[:id]).user
        
    unless current_user == cart_owner
      flash.notice = "Accès non autorisé."
      redirect_to root_path
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/create.html.erb
<h1>Carts#create</h1>
<p>Find me in app/views/carts/create.html.erb</p>

app/views/carts/delete.html.erb
<h1>Carts#delete</h1>
<p>Find me in app/views/carts/delete.html.erb</p>

app/views/carts/edit.html.erb
<h1>Carts#edit</h1>
<p>Find me in app/views/carts/edit.html.erb</p>

app/views/carts/index.html.erb
<h1>Carts#index</h1>
<p>Find me in app/views/carts/index.html.erb</p>

app/views/carts/new.html.erb
<h1>Carts#new</h1>
<p>Find me in app/views/carts/new.html.erb</p>

app/views/carts/show.html.erb
<%= link_to  "Retour à la liste des produits", root_path, class: "btn btn-outline-dark mt-5 mx-5"%>

<div class="container pt-5">
  <div class="row">
	<div class="col-md-12">
	  <h1>Cart (<%= current_user.cart.items.length %>)</h1>
	  <% if @current_user.cart.items.length < 1 %>
		<p>Your cart is empty.</p>
	  <% else %>
		<table class="table table-striped">
		  <thead>
			<tr>
			  <th>Product</th>
			  
			  <th>Price</th>

			  <th></th>
			  
			</tr>
		  </thead>
		  <tbody>
<% current_user.cart.cart_items.each do |cart_item| %>
              <tr>
                <td><%= cart_item.item.title %></td>
                
                <td><%= cart_item.item.price %>0€ </td>
                
                <td>
                  <%# <%= link_to "Remove", cart_items_path+"?item=#{item.id}", method: :delete, class: "btn btn-outline-danger" %> 
          <%= link_to "Remove", cart_item_path(cart_item), method: :delete, class: "btn btn-outline-danger" %>
          </td>
              </tr>
            <% end %>
		  </tbody>
		</table>
		<p>
		  <strong>Total: <%= @total %>0€</strong>
		</p>
		<% if @current_user.cart.items.length > 0 %>
		  <%= link_to 'Checkout', new_order_path+"?total=#{@total}", class:"btn btn-primary" %>
		<% else %>
		  <%= link_to 'Checkout', new_order_path+"?total=#{@total}", class:"btn btn-primary" %>
		<% end %>
	  <% end %>
	</div>
  </div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>