config/routes.rb
Rails.application.routes.draw do

root to:"items#index"
  devise_for :users
  
  
  resources :items
  resources :carts
  resources :orders
  resources :users
  resources :cart_items

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/item.rb
class Item < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  

  validates :title, 
    presence: true,
    length: { maximum: 30 }
  
  validates :description,
    presence: true,
    length: { in: 10..140 }

  validates :price,
    presence: true,
    numericality: { greater_than: 0 }

  validates :image_url,
    presence: true,
    format: URI::regexp(%w[http https])

  has_many :cart_items
  has_many :carts, through: :cart_items

  has_many :item_orders
  has_many :orders, through: :item_orders
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def show
    @item = Item.friendly.find(params[:id])
  end






end # end of class 'ItemsController'

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_items_list.html.erb
<!--<p>*mettre du code ici pour mettre en forme une 'card'*</p>

<ul>
  <% @items.each do |item|  %>    
    <li>
        <p>Item.title = <%= item.title  %><br/>
        Item.image_url = <%= item.image_url  %><br/>
        Item.description = <%= item.description  %><br/>
        Item.price = <%= item.price  %><br/>     
        </p>   
    </li>
  <% end %>
</ul> -->

<div class="row mx-auto mt-5">
  <% @items.each do |item|  %>
    <div class="col-sm-4 w-25 mx-auto">
      <div class="card border-dark text-center">
    <img class="card-img-top" src="<%=url_for(item.image_url)%>" alt="..." />
        <div class="card-body">
          <h5 class="card-title"><%=item.title%></h5>
          <p class="card-text"><%=item.price%>0€</p>
          <%= link_to "Voir", item_path(item), class:"btn btn-dark" %>
        </div>
      </div>
      <br/>
    </div>
  <% end %>
</div>         

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/index.html.erb
<!-- We call the partial dedicated to the molecule 'task_list' : -->
<%= render 'items_list' %>

<%= yield %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<%= link_to  "Retour à la liste des produits", root_path, class: "btn btn-outline-dark mt-5 mx-5"%>
         
         
          <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="<%=url_for(@item.image_url)%>" alt="..." /></div>
                    <div class="col-md-6">
                        
                        <h1 class="display-5 fw-bolder"><%= @item.title %></h1>
                        <div class="fs-5 mb-5">
                            <!-- minifix .0€-->
                            <span><%= @item.price %>0€</span>
                        </div>
                        <p class="lead"><%= @item.description %></p>
                        <div class="d-flex">
    <!--                        <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" /> -->
                                            <% if user_signed_in? %>
                            <%= link_to  "Add to cart", cart_items_path+"?item=#{@item.id}", method: :post, class: "btn btn-outline-dark flex-shrink-0"%>
                          <% else %>
                            <%= link_to  "Add to cart", new_user_session_path, class: "btn btn-outline-dark flex-shrink-0"%>
                          <%end%>

                        </div>
                    </div>
                </div>
            </div>
        </section>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>