config/routes.rb
Rails.application.routes.draw do

root to:"items#index"
  devise_for :users
  
  
  resources :items
  resources :carts
  resources :orders
  resources :users
  resources :cart_items

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_flashmessage.html.erb
  <!-- Affichage des messages de la méthode "flash" -->
    <% flash.each do |type, msg| %>
      <%= msg %>      
    <% end %>

app/views/layouts/_footer.html.erb
  <div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© Cute Cat Shop</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <%= image_tag "logomini.png", height: 48%>
    </a>

    <p class="nav col-md-4 justify-content-end text-muted">Toute demande de remboursement est inutile</p>

  </footer>
</div>

app/views/layouts/_jumbotron.html.erb
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Some Cute Cats</h1>
                    <p class="lead fw-normal text-white-50 mb-0">In a shop</p>
                </div>
            </div>
        </header>

app/views/layouts/_navbar.html.erb
        <nav class="navbar navbar-expand-lg navbar-light border-bottom">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href=<%=root_path%>><%= image_tag "logobis3.png"%> </a>
                <div class="container px-5">

                        <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %><br/>  
  
    <% else  %>
 <%= link_to "Sign up",  new_user_registration_path %> - <%= link_to "Sign In",  new_user_session_path %>
    <% end %>
                </div>
             <%if user_signed_in?%>
                 <%= link_to  "Cart", cart_path(current_user.id), class: "btn btn-outline-dark flex-shrink-0 bi-cart-fill me-1"%>
                       <%else%>
                         <%= link_to  "Cart", new_user_session_path, class: "btn btn-outline-dark flex-shrink-0 bi-cart-fill me-1"%>
                          <%end%>
                                        
                </div>
            </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
          <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
    <title>CuteCatShop</title>

        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
<!--        <link href="css/styles.css" rel="stylesheet" /> -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
  
<%= render partial: 'layouts/navbar' %>
<%= render partial: 'layouts/flashmessage' %>
<%= render partial: 'layouts/jumbotron' %>


    <%= yield %>
<%= render partial: 'layouts/footer' %>

  </body>

</html>